#!/bin/bash
DIR_INPUT=${1:-./input}
DIR_EXTRACT=./_extract
DIR_PARSE=./_parse
DIR_TOKEN=./token
DIR_TOKENFILE=./tokenline_num
DIR_DETECT=./_detect
DIR_DETECT2=./_detect2


echo "-- CCAligner --"
echo "input directory: ${DIR_INPUT}"
echo "output directorY: ${DIR_OUTPUT}"

rm -rf $DIR_EXTRACT 2> /dev/null
rm -rf $DIR_PARSE 2> /dev/null
rm $DIR_TOKENFILE 2> /dev/null
rm -rf $DIR_TOKEN 2> /dev/null
rm -rf $DIR_DETECT 2> /dev/null
rm -rf $DIR_DETECT2 2> /dev/null

mkdir $DIR_EXTRACT
mkdir $DIR_PARSE
mkdir $DIR_TOKEN
mkdir $DIR_DETECT
mkdir $DIR_DETECT2

# Compile
chmod +x txl/*.x extract parser tokenize detect co1

pushd lexical
make clean
make
popd


./extract ./txl java functions $DIR_INPUT $DIR_EXTRACT 8

./parser $DIR_EXTRACT $DIR_PARSE 5

./tokenize "${DIR_PARSE}/function.file" $DIR_TOKEN ./ 8

./detect $DIR_TOKEN $DIR_DETECT "${DIR_PARSE}/function.file" 6 1 0.6

./co1 $DIR_DETECT ./
